name: build
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: SCA-retireJS
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '18'
    # - run: npm install -g retire
    # - run: npm fund
    # - run: require --severity high --outputformat json --outputpath retirejs_output.json

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  test:
    name: test
    needs: Build # run only after build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3


